version: '2'
services:
  php:
    build: ./php
    ports:
      - "9000:9000"
    links:
      - mysql
      - memcache
      - redis
    volumes:
      - /data:/data
    restart: always

  nginx:
    depends_on:
      - php
    links:
      - php:php7
    build: ./nginx
    volumes:
      - /data:/data
    ports:
      - "80:80"
    restart: always

  mysql:
      build: ./mysql
      ports:
        - "3306:3306"
      volumes:
        - /data/data/mysql:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: 123456
      restart: always

  memcache:
      build: ./memcache
      ports:
        - "11211:11211"
      restart: always

  redis:
      build: ./redis
      ports:
        - "6379:6379"
      restart: always


